INCT-120 add input component w/ stories
elem15/inctagram pull request #21
Opened 2023-10-21 12:32 UTC by justSariox

2023-10-21 14:22 UTC, elem15 commented on src/shared/components/input/input.tsx
> +            <img src={SearchIcon} className={s.searchIcon} alt={'Search Icon'} />
Warnings use Image from Next

2023-10-21 14:22 UTC, elem15 commented on src/shared/components/input/input.tsx
> +              className={`${s.passwordControl} ${
You can use classnames or clsx. We should to choose one of them

2023-10-24 19:35 UTC, justSariox commented
resolve merge conflict

2023-10-25 09:23 UTC, elem15 requested changes

2023-10-30 19:02 UTC, closed without merging